# Generated by Django 3.2 on 2022-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('reason', models.CharField(choices=[('Level', 'My Language Level'), ('Booking', 'Existing Booking'), ('Help', 'Help with Website'), ('Private', 'Request private lesson'), ('Other', 'Other Inquiry')], default='Level', max_length=254)),
            ],
        ),
    ]
