# Generated by Django 3.2 on 2022-05-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.format'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'Bookable'), (0, 'Booking closed')], default=1),
        ),
    ]
