# Generated by Django 3.2 on 2022-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220531_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
