# Generated by Django 3.2 on 2022-05-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='time',
            new_name='starttime',
        ),
    ]
