# Generated by Django 3.2 on 2022-05-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_time_course_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='friendlyname',
        ),
    ]
