# Generated by Django 3.2 on 2022-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_format_friendlyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='friendlyname',
        ),
        migrations.AddField(
            model_name='level',
            name='part',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
